name: Run Python testsuite

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Make target executable
        run: |
          find target/string_bug -type f -exec chmod +x {} \;
          find target/bof -type f -exec chmod +x {} \;
          sudo bash -c "echo 'core' > /proc/sys/kernel/core_pattern";

      - name: Run testsuite
        env:
          TERM: xterm
        run: python3 tests/testsuite.py